apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.chain.name }}-bot-secret
type: Opaque
data:
  {{- range $key, $val := .Values.bot.secret }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
