apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.chain.name }}-service
  labels:
    {{- include "faucetbot.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.server.config.SMF_BOT_PORT }}
      name: metrics
      protocol: TCP
  selector:
    {{- include "faucetbot.selectorLabels" . | nindent 8 }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.chain.name }}-server-metrics
spec:
  selector:
    matchLabels:
    {{- include "faucetbot.selectorLabels" . | nindent 8 }}
  endpoints:
  - port: metrics
    interval: 15s
---
