apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.chain.name }}-server-secret
type: Opaque
data:
  {{- range $key, $val := .Values.server.secret }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
