services:
  faucet-server:
    container_name: faucet-server
    build:
      dockerfile: server_injected.Dockerfile
      context: ../
    environment:
      SMF_BACKEND_INJECTED_TYPES: "{}"
      SMF_BACKEND_BOT_PORT: 5555
      SMF_BACKEND_BOT_FAUCET_ACCOUNT_MNEMONIC: ${SMF_BACKEND_BOT_FAUCET_ACCOUNT_MNEMONIC:?BackendFaucetAccountMnemonicNotSet}
      SMF_BACKEND_DEPLOYED_REF: ${SMF_BACKEND_DEPLOYED_REF:?VERSION}
      SMF_BACKEND_DEPLOYED_TIME: ${SMF_BACKEND_DEPLOYED_TIME:?BUILD_DATE}
  faucet-bot:
    container_name: faucet-bot
    build:
      dockerfile: bot_injected.Dockerfile
      context: ../
    environment:
      SMF_BOT_FAUCET_IGNORE_LIST: ''
      SMF_BOT_BACKEND_URL: http://faucet-server:5555
      SMF_BOT_MATRIX_ACCESS_TOKEN: ${SMF_BOT_MATRIX_ACCESS_TOKEN:?BotmatrixAccessTokenNotSet}
      SMF_BOT_DEPLOYED_REF: ${SMF_BOT_DEPLOYED_REF:?VERSION}
      SMF_BOT_DEPLOYED_TIME: ${SMF_BOT_DEPLOYED_TIME:?BUILD_DATE}
