chain:
  name: westend

serviceAccount:
  create: true
  name: westend

server:
  secret:
    FAUCET_ACCOUNT_MNEMONIC: from-gitlab-ci-secret-variables
  config:
    RPC_ENDPOINT: "wss://westend-rpc.polkadot.io/"
    INJECTED_TYPES: '{}'

bot:
  secret:
    MATRIX_ACCESS_TOKEN: from-gitlab-ci-secret-variables
  config:
    # MATRIX_BOT_USER_ID: '@westend_faucet:matrix.org'
    MATRIX_BOT_USER_ID: '@test_bot_faucet:matrix.org'
    DRIP_AMOUNT: 0.5
    NETWORK_UNIT: WND
