[relaychain]
default_command = "polkadot"
default_args = [ "-lparachain=debug" ]

chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true
  ws_port = 9923

  [[relaychain.nodes]]
  name = "bob"
  validator = true

[[parachains]]
id = 1000

  [parachains.collator]
  name = "alice"
  ws_port = 9934
  command = "polkadot-parachain"
  args = ["-lparachain=debug"]


[[parachains]]
id = 1002
chain = "contracts-rococo-local"

  [parachains.collator]
  name = "contracts"
  ws_port = 9988
  command = "polkadot-parachain"
  args = ["-lparachain=debug", "--discover-local"]

