apiVersion: v2
name: substrate-faucet
description: A Helm chart for Kubernetes
type: application
version: 0.2.0
dependencies:
  - name: substrate-faucet
    version: "3.0.3"
    repository: "https://paritytech.github.io/helm-charts/"
