# name: GitHub Issue Sync

# on:
#   issues:
#     types:
#       - opened
#   workflow_dispatch:
#     inputs:
#       excludeClosed:
#         description: 'Exclude closed issues in the sync.'
#         type: boolean
#         default: true

# jobs:
#   sync:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Generate token
#         id: generate_token
#         uses: tibdex/github-app-token@v1
#         with:
#           app_id: ${{ secrets.PROJECT_APP_ID }}
#           private_key: ${{ secrets.PROJECT_APP_KEY }}
#       - name: Sync issues
#         uses: paritytech/github-issue-sync@v0.3
#         with:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           PROJECT_TOKEN: ${{ steps.generate_token.outputs.token }}
#           project: 16
#           project_field: Tool
#           project_value: polkadot-testnet-faucet
